name:                lichess-graphql-api
version:             0.1.0.0
github:              "githubuser/lichess-graphql-api"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lichess-graphql-api#readme>

dependencies:
- base >= 4.7 && < 5
- aeson == 1.2.4.0
- haxl == 2.0.0.0
- graphql-api == 0.3.0
- text == 1.2.3.0
- http-conduit == 2.3.1
- http-client-tls == 0.3.5.3
- hashable == 1.2.7.0

library:
  source-dirs: src

executables:
  lichess-graphql-api-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
      - TypeApplications
      - OverloadedStrings
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lichess-graphql-api

tests:
  lichess-graphql-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lichess-graphql-api
